### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by athulvingt** [meet-soni5720/Fight-Detection#2]
what is the tensorflow version used in the code? I tried tensorflow 1.14 but I got error
ModuleNotFoundError: No module named 'tensorflow.keras.applications.resnet'

on tensorflow 1.15 I am getting this error
SavedModel file does not exist at: model/fd_v2.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by meet-soni5720** [comment]
Use tensorflow version 2.0 and above, preferably 2.2 or 2.3, tell me if it solves the problem or not

**Comment by meet-soni5720** [comment]
i used tensorflow 2.2 for the project

**Comment by WenTaoLiu502** [comment]
@meet-soni5720 I have runned on tensorflow 2.2.0 today, and I met the same situation ‘SavedModel file does not exist at: model/fd_v2.h5/{saved_model.pbtxt|saved_model.pb}’. Maybe something wrong with the pretrained model，could you please upload it again? Thank you!

**Comment by meet-soni5720** [comment]
Try giving the full path like this: **python test.py -m D:/Fight-Detection/fight_detection_using_crnn/model/fd_v2.h5**  i tested it in mine pc with above command and works perfectly.
Tell me if it solves the problem or not.
i am also giving a link to download the weights if you want to:
https://drive.google.com/file/d/1S_bBYflp1bFBM1EtLxk4nhQ7adn1UjW_/view?usp=sharing

**Comment by WenTaoLiu502** [comment]
@meet-soni5720 Thanks for your link, the new downloaded model worked. So, I think it has something wrong with the current pretrained model.

**Comment by WenTaoLiu502** [comment]
@meet-soni5720 Thanks for your link, the new downloaded model worked. So, I think it has something wrong with the current pretrained model.

**Comment by meet-soni5720** [comment]
Okay thanks for update, i will put the link for download in readme so that others can download the model weights.
