### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by q865516854** [meet-soni5720/Fight-Detection#3]
What is a dataset？

**Comment by meet-soni5720** [comment]
https://www.kaggle.com/mohamedmustafa/real-life-violence-situations-dataset
This is a video dataset containing 1000 videos for violence and 1000 videos for non violence.

Any other larger dataset links for this purpose is welcomed.

**Comment by omtrix** [comment]
I have downloaded the project,as your advice in readme, I  set the path as : parser.add_argument('-m','--modelPath',required=True,default='./model/fd_v2.h5',help="path to model")
,however,  'test.py: error: the following arguments are required: -m/--modelPath' hapeened  
how can I finish detecting sucessfully?

**Comment by q865516854** [comment]
> I have downloaded the project,as your advice in readme, I set the path as : parser.add_argument('-m','--modelPath',required=True,default='./model/fd_v2.h5',help="path to model")
> ,however, 'test.py: error: the following arguments are required: -m/--modelPath' hapeened
> how can I finish detecting sucessfully?

Specify modelPath
